// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Teacher left":return img`
....................................
..............ffffff................
............fffeeeeeff..............
...........feeeeeeeeeeffff..........
..........feeeeeeeeeeeeeeef.........
.........ffeeeeeeeeeeeeeeeef........
........feeeffffffeeeeeeeeef........
.......feeefddddddfeeeeeeeeeff......
.......feeefdeddddfffeeeefeeef......
.......fefeeeeddddeeeeeefdfeef......
.......feffe18dddd881feeddfeef......
.......feefd18dddd881dffddfeef......
........fffd18dddd881ddddfeeeef.....
..........ffdddddddddddddffeeef.....
...........fddbbbdddddddf..feef.....
............fdddddddddff..fefeef....
.....f......fffffdddff....fefeef....
......f....66aaaddaaaaa6..feeeef....
.......f...66aaadaaaaa869..feeef....
........f....8999999968de9..feef....
.........f...8666666668de6..fef.....
..........f.f6999999968dde..ff......
...........fd688888888ddde..........
...........edd66666666ddde..........
...........ed699999996ddde..........
............e6999999966dee..........
............69999999996ee...........
............6999999999996...........
............6666666666666...........
...............11f..11f.............
...............fff..fff.............
....................................
....................................
....................................
....................................
....................................
`;
            case "image3":
            case "Teacher Screaming":return img`
....................................
.............f......fff.............
.....fff....fff..ffffeef............
....feeff...fef..feeefef............
....ffeeff.feeffffeeffff.fff........
......feef.feeeeeeeeeeefffefffff....
......feef.feeffffffffeeeeeeeeeff...
......feeffeefddddddddfeeeeeeefff...
......feeeeeefddddddddfeeefffff.....
......fffeeefddddddddddfeeef........
........ffefdeeeddddeeedfeeffff.....
.........fefddfffddfffddfeeeeeff....
......ffffefddffddddffddfeeeeeef....
......feeeefddffddddffddfeefffef....
......feeeffddd2dbbd2dddffff.fef....
.....ffefff.fdd2dbbd2ddf......ff....
.....feef..eeffddbbddffee...........
......fff.ed2eafd33dfaed2e..........
..........ed2eaaaddaaaedde..........
..........edde69999996edde..........
..........e2dd66699996d2de..........
...........eed69999966dee...........
.............e66669966e.............
..............68888886..............
..............66666666..............
..............69999996..............
.............6669999966.............
.............6996999996.............
............669999999966............
............699999999996............
............666666666666............
..............11f..f11..............
..............fff..fff..............
....................................
....................................
....................................
`;
            case "image1":
            case "Teacher right":return img`
....................................
................ffffff..............
..............ffeeeeefff............
..........ffffeeeeeeeeeef...........
.........feeeeeeeeeeeeeeef..........
........feeeeeeeeeeeeeeeeff.........
........feeeeeeeeeffffffeeef........
......ffeeeeeeeeefddddddfeeef.......
......feeefeeeefffddddedfeeef.......
......feefdfeeeeeeddddeeeefef.......
......feefddeef188dddd81effef.......
......feefddffd188dddd81dfeef.......
.....feeeefdddd188dddd81dfff........
.....feeeffdddddddddddddff..........
.....feef..fdddddddbbbddf...........
....feefef..ffdddddddddf............
....feefef....ffdddfffff......f.....
....feeeef..6aaaaaddaaa66....f......
....feeef..968aaaaadaaa66...f.......
....feef..9ed8699999998....f........
.....fef..6ed8666666668...f.........
......ff..edd8699999996f.f..........
..........eddd888888886df...........
..........eddd66666666dde...........
..........eddd699999996de...........
..........eed6699999996e............
...........ee69999999996............
...........6999999999996............
...........6666666666666............
.............f11..f11...............
.............fff..fff...............
....................................
....................................
....................................
....................................
....................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
